=== burnjiaozhen/minimybatis/src/main/java/com/lzp/mybatis/parsing/mybatis-1.0-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Roey
-->
<!ELEMENT configuration (environment?, mappers?)>

<!ELEMENT environments (environment+)>
<!ATTLIST environments
default CDATA #REQUIRED
>

<!ELEMENT environment (dataSource+)>
<!ATTLIST environment
default CDATA #REQUIRED
>

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource
id CDATA #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT mappers (mapper*)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
resource CDATA #IMPLIED
>

=== burnjiaozhen/minimybatis/src/main/resources/SqlMapConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration
        SYSTEM
        "minimybatis\src\main\java\com\lzp\mybatis\parsing\mybatis-1.0-config.dtd">
<configuration>
    <environment default="dev">
        <dataSource id="dev">
            <property name="driver" value="com.mysql.jdbc.Driver"/>
            <property name="url" value="jdbc:mysql://localhost:3306/minimybatis"/>
            <property name="username" value=""/>
            <property name="password" value=""/>
        </dataSource>
    </environment>
    <mappers>
        <mapper resource="com/lzp/dao/UserMapper.xml"/>
    </mappers>
</configuration>
